---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: CONTENT
- type: directory
  path: src/content/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - pages
- type: directory
  path: src/content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog
- type: heading
  label: CONFIG
- type: document
  path: src/config/site.config.json
  label: Site Config
- type: document
  path: src/config/menus.json
  label: Menus
- type: document
  path: src/config/footer.json
  label: Footer
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
