---
label: Input Configuration
hide_body: true
fields:
- name: configuration
  type: field_group
  config: {}
  fields:
  - name: size
    type: select
    default: Full
    config:
      required: true
      options:
      - Full
      - Half
      - Third
      - Quarter
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Size
    description: How big do you want the field to be?
  - name: required
    type: field_group
    config: {}
    fields:
    - name: value
      type: boolean
      label: Value
      default: true
    - name: message
      type: text
      config:
        required: false
      label: Message
      default: This field is required!
      showOnly:
        field: value
        value: true
    label: Required
  - name: minLength
    type: field_group
    config: {}
    fields:
    - name: value
      type: number
      label: Value
      description: ''
      default: 
      required: true
      config:
        min: 1
        max: 
        step: 1
    - name: message
      type: text
      config:
        required: false
      label: Message
      default: Not enough characters
    label: Minimum Length
  - name: maxLength
    type: field_group
    config: {}
    fields:
    - name: value
      type: number
      label: Value
      description: ''
      default: 
      required: true
      config:
        min: 1
        max: 
        step: 1
    - name: message
      type: text
      config:
        required: false
      label: Message
      default: Too many characters
    label: Maximum Length
  - name: pattern
    type: field_group
    config: {}
    fields:
    - name: value
      type: text
      config:
        required: false
      label: Value
    - name: message
      type: text
      config:
        required: false
        min: 1
      label: Message
      default: Invalid characters
    label: Pattern
  label: Configuration
